# Scope and purpose {.unnumbered}

This document captures discussion, pain points and a path to next steps 
after the R/Pharma events of 2023. There are two events that led to 
this document being created.

::: {.callout-note icon=false}

## {{< fa users >}} 2024 F2F Roundtables in Seattle

~120 leaders from 40+ companies met F2F in Seattle for a series of
discussions on the most pressing topics for late-stage reporting in R. 

The discussion was crowdsourced via a github discussion, and led to the 
following topics:

- [Transitioning our people from SAS to R](/change-management.html)
- [How best to engage and enable small/mid-size pharma to use R and open source tools](/smallmidpharma.html)
- [Future core competency of clinical statistical programmer with AI/LLM](/llms.html)
- [Can we do data storage and processing better in clinical trials?](/datatrials.html)
- [Sharing R data products externally](/rproducts.html)
- [Validation of shiny apps](/validate-shiny.html)
- [R package validation](/validate-package.html)
- [Leveraging operational metrics for better SCEs/platforms](/scemetrics.html)

:::

::: {.callout-note icon=false}

## {{< fa users >}} 2023 F2F Roundtables in Chicago

~60 leaders from 40+ companies met F2F in Chicago for a series of
discussions on the most pressing topics for late-stage reporting in R. 

The discussion was crowdsourced via a github discussion, and led to the 
following topics:

- [What are our goals for a modern clinical reporting workflow, on a modern SCE?](/modern-sce.html)
- [What are the risks with our increasing external business code dependencies?](/os-depends.html)
- [We have a path to R package validation - but what are we doing with shiny apps?](/validate-shiny.html)
- [What is the path to an interactive CSR?](/shiny-csr.html)
- [The case for contributing to OS](/case-os.html)
- [Where are we with our people?](/change-management.html)
- [What should we be doing to leverage advances in LLMs/AA/AI impact? (at the drug development through to developer efficiency levels)](/llms.html)
- [What are the barriers bringing imaging/genomics/digital biomarkers and the CRF closer?](/multi-modal.html)

:::

::: {.callout-note icon=false}

## {{< fa graduation-cap >}} References

[CAMIS - comparing differences based on tool used](https://psiaims.github.io/CAMIS/)

[PHUSE Open Source guidance](https://phuse-org.github.io/E2E-OS-Guidance/)

## 2024

[R Validation Hub update](https://pharmar.github.io/events-positconf2024/#/title-slide)

[2024 planning repo](https://rinpharma.github.io/rinpharma-summit-2024/)


## 2023

[R Validation Hub update](https://pharmar.github.io/events-rpharma2023/)

[Doug's slides on the shared validated repo](https://pharmar.github.io/events-positconf2023/#/title-slide)

[2023 planning repo](https://rinpharma.github.io/positconf-roundtables-2023/)


:::
